@startuml
'https://plantuml.com/class-diagram


interface EventI

interface DomainEventI

interface EventPublisher{
    + void publish(DomainEventI domainEvent)
}


class SeckillBaseEvent{
    - Long id
    - Integer status
    + SeckillBaseEvent(Long id, Integer status)
    + Long getId()
    + void setId(Long id)
    + Integer getStatus()
    + void setStatus(Integer status)
}

class SeckillOrderEvent{
    + SeckillOrderEvent(Long id, Integer status)
}

class LocalDomainEventPublisher{
    - EventBusI eventBus
    + void publish(DomainEventI domainEvent)
}

class SeckillOrderEventHandler{
    + Response execute(SeckillOrderEvent seckillOrderEvent)
}

EventI <|-- DomainEventI : 继承
DomainEventI <|..  SeckillBaseEvent : 实现
EventPublisher <|.. LocalDomainEventPublisher : 实现
DomainEventI <. LocalDomainEventPublisher : 依赖
SeckillBaseEvent <|- SeckillOrderEvent : 继承
SeckillOrderEvent <.. SeckillOrderEventHandler : 依赖
@enduml