@startuml
'https://plantuml.com/class-diagram


interface LocalCacheService<K, V>{
    + void put(K key, V value)
    + V getIfPresent(Object key)
}

class GuavaLocalCacheService<K, V>{
     + void put(K key, V value)
     + V getIfPresent(Object key)
}

class LocalCacheFactory{
    + {static}Cache<K, V> getLocalCache()
}

GuavaLocalCacheService ..> LocalCacheFactory : 依赖
GuavaLocalCacheService ..|> LocalCacheService : 实现

@enduml